import express from 'express'; import cors from 'cors'; import authRoutes from './routes/auth.routes.js'; import userRoutes from './routes/user.routes.js'; import farmRoutes from './routes/farm.routes.js'; import weatherRoutes from './routes/weather.routes.js'; import recommendationRoutes from './routes/recommendation.routes.js'; import { notFound, errorHandler } from './middleware/error.middleware.js';
const app = express();
app.disable('x-powered-by');
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173' }));
app.use(express.json({ limit: '20kb' })); app.use(express.urlencoded({ extended: false }));
app.get('/api/v1/health', (_req, res) => res.json({ success: true, message: 'Service is healthy', data: { status: 'ok' } }));
app.use('/api/v1/auth', authRoutes); 
app.use('/api/v1/users', userRoutes); 
app.use('/api/v1/farms', farmRoutes); 
app.use('/api/v1/weather', weatherRoutes); 
app.use('/api/v1/recommendations', recommendationRoutes);
app.use(notFound); app.use(errorHandler);
export default app;
