import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import authRoutes from './routes/auth.routes.js'; import userRoutes from './routes/user.routes.js'; import farmRoutes from './routes/farm.routes.js'; import weatherRoutes from './routes/weather.routes.js'; import recommendationRoutes from './routes/recommendation.routes.js'; import { notFound, errorHandler } from './middleware/error.middleware.js'; import { requireDatabase } from './middleware/database.middleware.js';
const app = express();
app.disable('x-powered-by');
export const normalizeOrigin = (origin = '') => origin.replace(/\/+$/, '');
const frontendOrigin = normalizeOrigin(process.env.FRONTEND_URL || 'http://localhost:5173');
app.use(cors({ origin: frontendOrigin }));
app.use(express.json({ limit: '20kb' })); app.use(express.urlencoded({ extended: false }));
app.use(requireDatabase);
app.get('/api/v1/health', (_req, res) => res.json({ success: true, message: 'Service is healthy', data: { status: 'ok', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected' } }));
app.use('/api/v1/auth', authRoutes); app.use('/api/v1/users', userRoutes); app.use('/api/v1/farms', farmRoutes); app.use('/api/v1/weather', weatherRoutes); app.use('/api/v1/recommendations', recommendationRoutes);
app.use(notFound); app.use(errorHandler);
export default app;
